### ISSUE TITLE
revert use of typescript target from es6 to es5

### ISSUE THREAD

**Issue by JacquesBergou** [jchiam/react-three-state-checkbox#13]
The typescript target in tsconfig.json has been [increased from es5 to es6](https://github.com/jchiam/react-three-state-checkbox/commit/289b88b61264831177cd54035b89d328218c68d1#diff-e5e546dd2eb0351f813d63d1b39dbc48):

This lead to errors in minification process in create-react-app 
cf: 
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify
and also break the generated bundle to run on IE11
Can you please revert to target es5? Thanks

**Comment by jchiam** [comment]
>npm run build fails to minify
Before react-scripts@2.0.0, this problem was caused by third party node_modules using modern JavaScript features because the minifier couldn't handle them during the build. This has been solved by compiling standard modern JavaScript features inside node_modules in react-scripts@2.0.0 and higher.

>If you're seeing this error, you're likely using an old version of react-scripts. You can either fix it by avoiding a dependency that uses modern syntax, or by upgrading to react-scripts@>=2.0.0 and following the migration instructions in the changelog.

Sorry, I'm not very familiar with `create-react-app`, but would upgrading `react-scripts` solve your problem?

**Comment by JacquesBergou** [comment]
using react-scripts@2.0.5 fixed the issue
thank!
